### ISSUE TITLE
[feature request] transform the base64 coding image to a single file

### ISSUE THREAD

**Issue by Asynchro-Epool** [reorx/obsidian-paste-image-rename#17]
When pasting a image into obsidian, sometimes (from zotero) the picture save with the format of base64 other than a single file. What I hope to do is use the *Paste image rename* command to transform the base64 image to a single file. 

I will appreaciate it if you can provide this function.

**Comment by reorx** [comment]
I totally understand your situation, but I'm afraid this is not very suitable to implement in this plugin. Paste image rename listens to the vault's new file event, not the clipboard paste event, because it's very hard (at least I cannot find a way) to save the data from the clipboard to the filesystem on my own. Therefore, the plugin has no idea about clipboard data, not to mention read and convert it.

I think your idea could be turned into a new plugin, which opens a textarea to input base64 or [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) and turns it into an image. When the image is created, Paste image rename will be triggered to handle the renaming process.

**Comment by Asynchro-Epool** [comment]
> I totally understand your situation, but I'm afraid this is not very suitable to implement in this plugin. Paste image rename listens to the vault's new file event, not the clipboard paste event, because it's very hard (at least I cannot find a way) to save the data from the clipboard to the filesystem on my own. Therefore, the plugin has no idea about clipboard data, not to mention read and convert it.
> 
> I think your idea could be turned into a new plugin, which opens a textarea to input base64 or [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) and turns it into an image. When the image is created, Paste image rename will be triggered to handle the renaming process.

I guess this function is not neccessary to listen clipboard. There is a way that reading markdown base64 text and transforming it to image. Thus, it does need a extra-plugin.

There are some codes which could be good reference.

```javascript
var imageData = atob(base64Text);

var arrayBuffer = new Uint8Array(imageData.length);
for (var i = 0; i < imageData.length; i++) {
    arrayBuffer[i] = imageData.charCodeAt(i);
}

var blob = new Blob([arrayBuffer], {type: "image/jpeg"});

var imageUrl = URL.createObjectURL(blob);

var imgElement = document.getElementById("my-image");
imgElement.src = imageUrl;
```

```javascript
fetch(base64Text)
    .then(res => res.blob())
    .then(blob => {
        let imgUrl = URL.createObjectURL(blob)
        let img = document.createElement('img')
        img.src = imgUrl;
        document.body.appendChild(img)
    })
```
