### ISSUE TITLE
Auto rename doesn't always work when pasting

### ISSUE THREAD

**Issue by rrigobello** [reorx/obsidian-paste-image-rename#20]
It seems that, on average, the plugin fails to trigger roughly 50% of the times when pasting images into a note.

**Comment by pm64** [comment]
I have not yet managed to see the plugin working at all. In my testing I'm doing the copy from Firefox for Windows, the "Handle all attachments" plugin option is enabled, and all other settings are set to defaults. Perhaps obsidian-paste-image-rename is incompatible with Obsidian 0.15.9?

**Comment by 23727** [comment]
Plug-in also is not working for me.

I paste images into excalidraw, and I was hoping this plug-in would be able to rename the files; however, it does not appear to function.

**Comment by reorx** [comment]
This problem might be fixed in [1.6.0](https://github.com/reorx/obsidian-paste-image-rename/releases/tag/1.6.0), but I'm not 100% sure since it lacks context. You can try updating the plugin and see if it works for you. If not, feel free to re-open this issue.

@23727 for the excalidraw issue, because pasting in excalidraw doesn't actually create a new file, the behavior that no renaming modal appears is expected.

**Comment by nprime496** [comment]
Jan 2024, it seems to work randomly and can't be reliable even for simple images format like png.

Is there any explanation about why it bugs in the first time ?


Edit: I did not understand how the plugin works. It is activated only after `Ctrl+V` command not on drag'n drop. My issue is more related to #25 and #79.
